version: '3'

services:
    artalk:
        image: artalk/p2p:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: artalk
        hostname: artalk
        volumes:
            - .env:/src/.env:ro
            # These volumes are not mandatory, uncomment if you want to use it
            # - ./app/:/src/app/:ro
            # - ./public/:/src/public/:ro
        restart: unless-stopped
        ports:
            - '${PORT}:${PORT}'
# Uncomment below, remove "ports:" section above and configure labels as
# needed for LetsEncrypt TLS certificates with Traefik.
# See https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
#   expose:
#     - 3000
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.routers.artalk.rule=Host(`artalk.example.com`)"
#     - "traefik.http.routers.artalk.entrypoints=websecure"
#     - "traefik.http.routers.artalk.tls.certresolver=myresolver"
#     - "traefik.http.services.artalk.loadbalancer.server.port=3000"
